name: Close inactive issues
on:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 15
          days-before-issue-close: 10
          stale-issue-label: "inactive"
          stale-issue-message: "This issue is labeled `inactive` because it has been open for 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being labeled as `inactive`."
          days-before-pr-stale: -1
          days-before-pr-close: -1
