name: check-bad-words
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check for bad words, such as bad, worse etc.
        run: ./scripts/check_bad_words.sh
